# Generated by Django 3.0.3 on 2020-03-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('runningAvgClosePrice', models.FloatField()),
                ('runningAvgTradePrice', models.FloatField()),
                ('runningAvgQuantity', models.FloatField()),
                ('totalEntries', models.IntegerField()),
                ('totalQuantity', models.BigIntegerField()),
                ('trades', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val1', models.FloatField()),
                ('val2', models.FloatField()),
                ('val3', models.FloatField()),
                ('val4', models.FloatField()),
                ('val5', models.FloatField()),
                ('val6', models.FloatField()),
                ('val7', models.FloatField()),
                ('val8', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_val', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
                ('new_val', models.CharField(max_length=50)),
                ('times_corrected', models.IntegerField()),
            ],
            options={
                'unique_together': {('old_val', 'field', 'new_val')},
            },
        ),
    ]
