# Generated by Django 3.0.3 on 2020-03-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
