# Generated by Django 3.0.2 on 2020-01-22 22:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DerivativeTrade',
            fields=[
                ('trade_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('date_of_trade', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_type', models.CharField(choices=[('S', 'Stocks'), ('P', 'Product')], default='S', max_length=1)),
                ('notional_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('notional_currency', models.CharField(max_length=3)),
                ('quantity', models.IntegerField()),
                ('maturity_date', models.DateField()),
                ('underlying_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('underlying_currency', models.CharField(max_length=3)),
                ('strike_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('buying_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_buying', to='trades.Company')),
                ('selling_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_selling', to='trades.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('seller_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('value', models.DecimalField(decimal_places=6, max_digits=16)),
            ],
            options={
                'unique_together': {('date', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Company')),
            ],
            options={
                'unique_together': {('date', 'company')},
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Product')),
            ],
            options={
                'unique_together': {('date', 'product')},
            },
        ),
        migrations.CreateModel(
            name='DerivativeTradeProduct',
            fields=[
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trades.DerivativeTrade')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Product')),
            ],
        ),
    ]
