# Generated by Django 3.0.2 on 2020-01-20 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trades.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Products')),
            ],
        ),
        migrations.CreateModel(
            name='DerivativeTrades',
            fields=[
                ('date_of_trade', models.DateTimeField()),
                ('trade_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('notional_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('maturity_date', models.DateField()),
                ('underlying_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buying_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_company', to='trades.Company')),
                ('notional_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notional_currency', to='trades.Currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Products')),
                ('selling_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_company', to='trades.Company')),
                ('underlying_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underlying_currency', to='trades.Currency')),
            ],
        ),
        migrations.AddField(
            model_name='currency',
            name='values',
            field=models.ManyToManyField(to='trades.CurrencyValues'),
        ),
    ]
