# Generated by Django 3.0.2 on 2020-01-22 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derivativetrade',
            name='product',
        ),
        migrations.AddField(
            model_name='derivativetrade',
            name='product_type',
            field=models.CharField(choices=[('S', 'Stocks'), ('P', 'Product')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='derivativetrade',
            name='date_of_trade',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
