# Generated by Django 3.0.2 on 2020-01-27 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivativetradeproduct',
            name='trade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='traded_product', serialize=False, to='trades.DerivativeTrade'),
        ),
    ]
