# Generated by Django 3.0.2 on 2020-01-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20200127_0050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DerivativeTradeProduct',
            new_name='TradeProduct',
        ),
    ]
