# Generated by Django 3.0.2 on 2020-01-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20200122_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivativeTradeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Product')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.DerivativeTrade')),
            ],
        ),
    ]
