# Generated by Django 3.0.2 on 2020-03-02 20:43

from django.db import migrations, models
import trades.models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_auto_20200127_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=trades.models.generate_company_id, max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
