# Generated by Django 3.0.2 on 2020-03-02 22:23

from django.db import migrations, models
import trades.models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_auto_20200302_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derivativetrade',
            name='notional_amount',
        ),
        migrations.AlterField(
            model_name='derivativetrade',
            name='trade_id',
            field=models.CharField(default=trades.models.generate_trade_id, max_length=16, primary_key=True, serialize=False),
        ),
    ]
