# Generated by Django 3.0.2 on 2020-01-22 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_auto_20200122_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivativetrade',
            name='buying_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_buying', to='trades.Company'),
        ),
        migrations.AlterField(
            model_name='derivativetrade',
            name='selling_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_selling', to='trades.Company'),
        ),
    ]
