# Generated by Django 3.0.2 on 2020-01-22 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_auto_20200122_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derivativetradeproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='derivativetradeproduct',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trades.DerivativeTrade'),
        ),
    ]
