# Generated by Django 3.0.2 on 2020-01-22 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_auto_20200122_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivativetradeproduct',
            name='trade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trades.DerivativeTrade'),
        ),
    ]
